In [1]:
from datasets import load_dataset
import pandas as pd

In [2]:
# Login using e.g. `huggingface-cli login` to access this dataset
ds = load_dataset("Tobi-Bueck/customer-support-tickets")
ds

DatasetDict({
    train: Dataset({
        features: ['subject', 'body', 'answer', 'type', 'queue', 'priority', 'language', 'version', 'tag_1', 'tag_2', 'tag_3', 'tag_4', 'tag_5', 'tag_6', 'tag_7', 'tag_8'],
        num_rows: 61765
    })
})

In [3]:
df = pd.DataFrame(ds["train"])
df.head()

,subject,body,answer,type,queue,priority,language,version,tag_1,tag_2,tag_3,tag_4,tag_5,tag_6,tag_7,tag_8
0,Wesentlicher Sicherheitsvorfall,"Sehr geehrtes Support-Team,\n\nich möchte eine...",Vielen Dank für die Meldung des kritischen Sic...,Incident,Technical Support,high,de,51.0,Security,Outage,Disruption,Data Breach,NaN,NaN,NaN,NaN
1,Account Disruption,"Dear Customer Support Team,\n\nI am writing to...","Thank you for reaching out, <name>. We are awa...",Incident,Technical Support,high,en,51.0,Account,Disruption,Outage,IT,Tech Support,NaN,NaN,NaN
2,Query About Smart Home System Integration Feat...,"Dear Customer Support Team,\n\nI hope this mes...",Thank you for your inquiry. Our products suppo...,Request,Returns and Exchanges,medium,en,51.0,Product,Feature,Tech Support,NaN,NaN,NaN,NaN,NaN
3,Inquiry Regarding Invoice Details,"Dear Customer Support Team,\n\nI hope this mes...",We appreciate you reaching out with your billi...,Request,Billing and Payments,low,en,51.0,Billing,Payment,Account,Documentation,Feedback,NaN,NaN,NaN
4,Question About Marketing Agency Software Compa...,"Dear Support Team,\n\nI hope this message reac...",Thank you for your inquiry. Our product suppor...,Problem,Sales and Pre-Sales,medium,en,51.0,Product,Feature,Feedback,Tech Support,NaN,NaN,NaN,NaN

In [4]:
df_english = df[df["language"] == "en"]
df_english.shape

(28261, 16)

In [5]:
df_english.head()
df_english.columns

Index(['subject', 'body', 'answer', 'type', 'queue', 'priority', 'language',
       'version', 'tag_1', 'tag_2', 'tag_3', 'tag_4', 'tag_5', 'tag_6',
       'tag_7', 'tag_8'],
      dtype='str')

In [6]:
df_selected = df_english[["subject","body", "priority", "queue"]]
df_selected.head()

,subject,body,priority,queue
1,Account Disruption,"Dear Customer Support Team,\n\nI am writing to...",high,Technical Support
2,Query About Smart Home System Integration Feat...,"Dear Customer Support Team,\n\nI hope this mes...",medium,Returns and Exchanges
3,Inquiry Regarding Invoice Details,"Dear Customer Support Team,\n\nI hope this mes...",low,Billing and Payments
4,Question About Marketing Agency Software Compa...,"Dear Support Team,\n\nI hope this message reac...",medium,Sales and Pre-Sales
5,Feature Query,"Dear Customer Support,\n\nI hope this message ...",high,Technical Support

In [7]:
df_selected["body"].iloc[0]

'Dear Customer Support Team,\\n\\nI am writing to report a significant problem with the centralized account management portal, which currently appears to be offline. This outage is blocking access to account settings, leading to substantial inconvenience. I have attempted to log in multiple times using different browsers and devices, but the issue persists.\\n\\nCould you please provide an update on the outage status and an estimated time for resolution? Also, are there any alternative ways to access and manage my account during this downtime?'

In [8]:
df_selected["priority"].unique(),df_selected["queue"].unique(),df_selected["subject"].unique()

(<ArrowStringArray>
 ['high', 'medium', 'low']
 Length: 3, dtype: str,
 <ArrowStringArray>
 [              'Technical Support',           'Returns and Exchanges',
             'Billing and Payments',             'Sales and Pre-Sales',
  'Service Outages and Maintenance',                 'Product Support',
                       'IT Support',                'Customer Service',
                  'Human Resources',                 'General Inquiry']
 Length: 10, dtype: str,
 <ArrowStringArray>
 [                                              'Account Disruption',
                'Query About Smart Home System Integration Features',
                                 'Inquiry Regarding Invoice Details',
            'Question About Marketing Agency Software Compatibility',
                                                     'Feature Query',
                                              'System Interruptions',
                 'Connectivity Problems with Printer on MacBook Pro',
                                                  'VPN Access Issue',
  'Immediate Help Needed: Technical Problem with Cloud SaaS Service',
              'Inquiry for Detailed Information on Agency Offerings',
  ...
                                    'Report on Data Security Breach',
                        'Concerns Over Medical Data Security Breach',
                'Improve Investment Portfolio with Machine Learning',
                                    'Investment Returns Discrepancy',
        'Unanticipated Crash of Investment Data Analytics Dashboard',
                  'Strategies for Enhancing Smart-Smoke-Alarm Sales',
                  'Enhancing Firm's Investment Portfolio Management',
                        'Boost Digital Marketing Content Production',
                        'Investment Modeling Results Are Inaccurate',
                'Guidelines for Securing Medical Data in OBS Studio']
 Length: 19065, dtype: str)

In [9]:
import re

category_keywords = {
    "account": [
        "account", "access", "disruption", "profile", "user"
    ],
    "billing": [
        "invoice", "billing", "payment", "refund", "pricing"
    ],
    "bug": [
        "bug", "error", "issue", "problem", "inaccurate", "failure"
    ],
    "deployment": [
        "deploy", "deployment", "release", "rollout", "installation"
    ],
    "infrastructure": [
        "outage", "interrupt", "maintenance", "downtime", "system interruption"
    ],
    "integration": [
        "integration", "compatibility", "api", "connect", "smart home"
    ],
    "login": [
        "login", "sign in", "authentication", "password", "access issue"
    ],
    "network": [
        "network", "connectivity", "vpn", "printer", "wifi"
    ],
    "security": [
        "security", "breach", "data leak", "privacy", "secure"
    ]
}

In [10]:
def classify_subject(subject):
    if not isinstance(subject, str):
        return "other"   # handle NaN / non-text safely

    subject = subject.lower()

    for category, keywords in category_keywords.items():
        for keyword in keywords:
            if keyword in subject:
                return category

    return "other"

df_selected["category"] = df_selected["subject"].apply(classify_subject)
df_selected.head()

,subject,body,priority,queue,category
1,Account Disruption,"Dear Customer Support Team,\n\nI am writing to...",high,Technical Support,account
2,Query About Smart Home System Integration Feat...,"Dear Customer Support Team,\n\nI hope this mes...",medium,Returns and Exchanges,integration
3,Inquiry Regarding Invoice Details,"Dear Customer Support Team,\n\nI hope this mes...",low,Billing and Payments,billing
4,Question About Marketing Agency Software Compa...,"Dear Support Team,\n\nI hope this message reac...",medium,Sales and Pre-Sales,integration
5,Feature Query,"Dear Customer Support,\n\nI hope this message ...",high,Technical Support,other

In [11]:
for i in range(10):
    print(f"Row {i}:")
    print(df_selected["body"].iloc[i])

Row 0:
Dear Customer Support Team,\n\nI am writing to report a significant problem with the centralized account management portal, which currently appears to be offline. This outage is blocking access to account settings, leading to substantial inconvenience. I have attempted to log in multiple times using different browsers and devices, but the issue persists.\n\nCould you please provide an update on the outage status and an estimated time for resolution? Also, are there any alternative ways to access and manage my account during this downtime?
Row 1:
Dear Customer Support Team,\n\nI hope this message reaches you well. I am reaching out to request detailed information about the capabilities of your smart home integration products listed on your website. As a potential customer aiming to develop a seamlessly interconnected home environment, it is essential to understand how your products interact with various smart home platforms.\n\nCould you kindly provide detailed compatibility information with popular smart home ecosystems such as Amazon Alexa, Google Assistant, and Apple?
Row 2:
Dear Customer Support Team,\n\nI hope this message finds you well. I am reaching out to request clarification about the billing and payment procedures linked to my account. Recently, I observed some inconsistencies in the charges applied and would like to ensure I fully understand the billing cycle, accepted payment options, and any potential extra charges.\n\nFirstly, I would be grateful if you could provide a detailed explanation of how the billing cycle functions. Specifically, I am interested in knowing the start and end dates.\n\nThank you for your assistance regarding these billing inquiries.
Row 3:
Dear Support Team,\n\nI hope this message reaches you well. I am reaching out to ask about the compatibility of your products with the specific needs of marketing agencies. Our company is considering adopting these solutions to streamline our current marketing processes and wants to confirm that the products are fully compatible with the tools and platforms we currently utilize.\n\nCould you please supply detailed information regarding the compatibility of your products with popular marketing software, CRM systems, email marketing applications, and analytics platforms? Additionally, I would appreciate any relevant case studies or documentation tailored to our use case.
Row 4:
Dear Customer Support,\n\nI hope this message reaches you in good health. I am eager to learn more about the features of one of your products. Would you be able to share comprehensive details about its functionalities, specifications, and any distinctive characteristics it may possess? Additionally, if there are user manuals, tutorials, or demonstration videos available, I would be grateful if you could provide those resources. Gaining a thorough understanding of the features will assist me in making an informed decision regarding the product.\n\nThank you very much for your assistance. I look forward to your prompt reply.\n\nBest regards
Row 5:
Dear Customer Support Team,\n\nI am submitting a report regarding multiple system service disruptions that are currently interfering with project operations and client interactions. These interruptions have notably reduced efficiency and caused delays in meeting important deadlines.\n\nInitial assessments suggest that the primary issue may be linked to widespread failures in network hardware connectivity. We have already carried out several basic troubleshooting procedures, such as rebooting devices and performing initial system checks, but the problems persist.
Row 6:
Dear Support Team,\n\nI am reporting a recurring issue with the Laser Printer when printing from MacBook Pros running macOS 15. Several team members have recently encountered this problem, which appears to be connected to the latest macOS 15 system updates.\n\nWe believe the root cause might be a driver compatibility issue due to the updated operating systems or printer firmware. To troubleshoot, we have restarted the printers and MacBook devices, reinstalled the printer drivers, and verified configurations.
Row 7:
Customer Support,\n\nWe are encountering a disruption in VPN-router connectivity that is impacting several devices, notably essential remote telemedicine systems and EMR integrations. Attempts to resolve the issue by restarting affected devices and resetting the router have been unsuccessful. We suspect the problem may be related to firmware discrepancies following recent network configuration updates. This disruption is significantly affecting our operations, and we urgently need assistance to identify and fix the root cause. Kindly advise on additional troubleshooting steps.
Row 8:
Dear Customer Support Team,\n\nI am submitting a report regarding a technical problem encountered with the Cloud SaaS platform, which is currently disrupting our business activities. I have observed that certain features are not functioning as expected, causing interruptions that hinder workflow efficiency.\n\nIn particular, I am facing sporadic connectivity issues when trying to access the platform. Sometimes, the system fails to load the dashboard, and the data displayed appears outdated or incomplete. Furthermore, the response times for executing commands have significantly increased, resulting in delays.
Row 9:
Dear Customer Support Team,\n\nI hope this message reaches you well. I am writing to request detailed information about the services provided by your agency. Specifically, I am interested in understanding the variety of services available, the pricing models, and any special packages or offers that might be applicable.\n\nAdditionally, I would appreciate it if you could send brochures, service contracts, and case studies highlighting your previous work and client success stories. This information will greatly help me in making an informed decision.

In [12]:
df_selected["description"] = df_selected["subject"] + " " + df_selected["body"]
df_selected.head()

,subject,body,priority,queue,category,description
1,Account Disruption,"Dear Customer Support Team,\n\nI am writing to...",high,Technical Support,account,"Account Disruption Dear Customer Support Team,..."
2,Query About Smart Home System Integration Feat...,"Dear Customer Support Team,\n\nI hope this mes...",medium,Returns and Exchanges,integration,Query About Smart Home System Integration Feat...
3,Inquiry Regarding Invoice Details,"Dear Customer Support Team,\n\nI hope this mes...",low,Billing and Payments,billing,Inquiry Regarding Invoice Details Dear Custome...
4,Question About Marketing Agency Software Compa...,"Dear Support Team,\n\nI hope this message reac...",medium,Sales and Pre-Sales,integration,Question About Marketing Agency Software Compa...
5,Feature Query,"Dear Customer Support,\n\nI hope this message ...",high,Technical Support,other,"Feature Query Dear Customer Support,\n\nI hope..."

In [13]:
new_data = pd.DataFrame({"description": df_selected["description"]})
new_data.head()

                                         description
1  Account Disruption Dear Customer Support Team,...
2  Query About Smart Home System Integration Feat...
3  Inquiry Regarding Invoice Details Dear Custome...
4  Question About Marketing Agency Software Compa...
5  Feature Query Dear Customer Support,\n\nI hope...

In [14]:
new_data.to_csv("customer_support_tickets.csv", index=True)

In [2]:
import pandas as pd

df = pd.read_csv("classified_tickets.csv")
df.head()

   id                                        description  category priority
0   1  Account Disruption Dear Customer Support Team,...   account     High
1   2  Query About Smart Home System Integration Feat...  security     High
2   3  Inquiry Regarding Invoice Details Dear Custome...   account     High
3   4  Question About Marketing Agency Software Compa...  security     High
4   5  Feature Query Dear Customer Support,\n\nI hope...  security     High

In [3]:
for i in range(10):
    print(f"Row {i}:")
    print(df["description"].iloc[i])

Row 0:
Account Disruption Dear Customer Support Team,\n\nI am writing to report a significant problem with the centralized account management portal, which currently appears to be offline. This outage is blocking access to account settings, leading to substantial inconvenience. I have attempted to log in multiple times using different browsers and devices, but the issue persists.\n\nCould you please provide an update on the outage status and an estimated time for resolution? Also, are there any alternative ways to access and manage my account during this downtime?
Row 1:
Query About Smart Home System Integration Features Dear Customer Support Team,\n\nI hope this message reaches you well. I am reaching out to request detailed information about the capabilities of your smart home integration products listed on your website. As a potential customer aiming to develop a seamlessly interconnected home environment, it is essential to understand how your products interact with various smart home platforms.\n\nCould you kindly provide detailed compatibility information with popular smart home ecosystems such as Amazon Alexa, Google Assistant, and Apple?
Row 2:
Inquiry Regarding Invoice Details Dear Customer Support Team,\n\nI hope this message finds you well. I am reaching out to request clarification about the billing and payment procedures linked to my account. Recently, I observed some inconsistencies in the charges applied and would like to ensure I fully understand the billing cycle, accepted payment options, and any potential extra charges.\n\nFirstly, I would be grateful if you could provide a detailed explanation of how the billing cycle functions. Specifically, I am interested in knowing the start and end dates.\n\nThank you for your assistance regarding these billing inquiries.
Row 3:
Question About Marketing Agency Software Compatibility Dear Support Team,\n\nI hope this message reaches you well. I am reaching out to ask about the compatibility of your products with the specific needs of marketing agencies. Our company is considering adopting these solutions to streamline our current marketing processes and wants to confirm that the products are fully compatible with the tools and platforms we currently utilize.\n\nCould you please supply detailed information regarding the compatibility of your products with popular marketing software, CRM systems, email marketing applications, and analytics platforms? Additionally, I would appreciate any relevant case studies or documentation tailored to our use case.
Row 4:
Feature Query Dear Customer Support,\n\nI hope this message reaches you in good health. I am eager to learn more about the features of one of your products. Would you be able to share comprehensive details about its functionalities, specifications, and any distinctive characteristics it may possess? Additionally, if there are user manuals, tutorials, or demonstration videos available, I would be grateful if you could provide those resources. Gaining a thorough understanding of the features will assist me in making an informed decision regarding the product.\n\nThank you very much for your assistance. I look forward to your prompt reply.\n\nBest regards
Row 5:
System Interruptions Dear Customer Support Team,\n\nI am submitting a report regarding multiple system service disruptions that are currently interfering with project operations and client interactions. These interruptions have notably reduced efficiency and caused delays in meeting important deadlines.\n\nInitial assessments suggest that the primary issue may be linked to widespread failures in network hardware connectivity. We have already carried out several basic troubleshooting procedures, such as rebooting devices and performing initial system checks, but the problems persist.
Row 6:
Connectivity Problems with Printer on MacBook Pro Dear Support Team,\n\nI am reporting a recurring issue with the Laser Printer when printing from MacBook Pros running macOS 15. Several team members have recently encountered this problem, which appears to be connected to the latest macOS 15 system updates.\n\nWe believe the root cause might be a driver compatibility issue due to the updated operating systems or printer firmware. To troubleshoot, we have restarted the printers and MacBook devices, reinstalled the printer drivers, and verified configurations.
Row 7:
VPN Access Issue Customer Support,\n\nWe are encountering a disruption in VPN-router connectivity that is impacting several devices, notably essential remote telemedicine systems and EMR integrations. Attempts to resolve the issue by restarting affected devices and resetting the router have been unsuccessful. We suspect the problem may be related to firmware discrepancies following recent network configuration updates. This disruption is significantly affecting our operations, and we urgently need assistance to identify and fix the root cause. Kindly advise on additional troubleshooting steps.
Row 8:
Immediate Help Needed: Technical Problem with Cloud SaaS Service Dear Customer Support Team,\n\nI am submitting a report regarding a technical problem encountered with the Cloud SaaS platform, which is currently disrupting our business activities. I have observed that certain features are not functioning as expected, causing interruptions that hinder workflow efficiency.\n\nIn particular, I am facing sporadic connectivity issues when trying to access the platform. Sometimes, the system fails to load the dashboard, and the data displayed appears outdated or incomplete. Furthermore, the response times for executing commands have significantly increased, resulting in delays.
Row 9:
Inquiry for Detailed Information on Agency Offerings Dear Customer Support Team,\n\nI hope this message reaches you well. I am writing to request detailed information about the services provided by your agency. Specifically, I am interested in understanding the variety of services available, the pricing models, and any special packages or offers that might be applicable.\n\nAdditionally, I would appreciate it if you could send brochures, service contracts, and case studies highlighting your previous work and client success stories. This information will greatly help me in making an informed decision.